name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install Dependencies
        run: |
          gem install bundler

      - name: Install Gems
        run: |
          bundle install

      - name: Run Tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:@localhost:5432/github_actions_test
          RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}

        run: |
          bundle exec rails db:prepare
          bundle exec rails test

      - name: Create Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ","
      - name: Show String
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "CHANGED $CHANGED_FILES"
      - name: Run Brakeman
        uses: artplan1/brakeman-action@v1.2.1
        with:
          flags: "--color --only-files ${{ steps.changed-files.outputs.all_changed_files }}"
      # - name: Install Brakeman
      #   run: |
      #     gem install bundler
      #     bundle install
      #     mkdir tmp
      #     brakeman -f json > tmp/brakeman.json || exit 0

      # - name: Create Security Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: security-artifact
      #     path: tmp/brakeman.json
